apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "matomo.fullname" . }}
  labels:
    app: {{ template "matomo.name" . }}
    chart: {{ template "matomo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "matomo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "matomo.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.matomoNginx.image.repository }}:{{ .Values.matomoNginx.image.tag }}"
          imagePullPolicy: {{ .Values.matomoNginx.image.pullPolicy }}
          command: ["nginx", "-g", "daemon off;", "-c", "/config/nginx.conf"]
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /var/www/html
              name: html-files
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "matomo.fullname" . }}-config
            - secretRef:
                name: {{ template "matomo.fullname" . }}-secrets
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: html-files
{{- if .Values.php.no_install }}
            - mountPath: /var/www/html/config
              name: php-config
            - mountPath: /var/www/html/config
              name: htaccess
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
{{- if .Values.php.no_install }}
      - name: php-config
        secret:
          defaultMode: 622
          secretName: {{ template "matomo.fullname" . }}-config-ini-php-secrets
      - name: htaccess
        configmap:
          defaultMode: 622
          name: {{ template "matomo.fullname" . }}-htaccess
{{- end }}
      - name: config
        configMap:
          name: {{ template "matomo.fullname" . }}
      - name: html-files
        emptyDir: {}
