apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matomo.fullname" . }}-secrets
type: Opaque
data:
  MATOMO_DATABASE_USERNAME: {{ template "matomo.db.username" . }}
  MATOMO_DATABASE_PASSWORD: {{ template "matomo.db.password" . }}